# Default values for sigscale-ocs
#
replicaCount: 1
image:
  repository: sigscale/ocs
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
restService:
  type: LoadBalancer
  clusterIP: ""
  port: 80
diameterAcctService:
  create: true
  type: ClusterIP
  protocol: TCP
  clusterIP: ""
  port: 3868
diameterAuthService:
  create: true
  type: ClusterIP
  protocol: TCP
  clusterIP: ""
  port: 3869
radiusAcctService:
  create: true
  type: ClusterIP
  clusterIP: ""
  port: 1813
radiusAuthService:
  create: true
  type: ClusterIP
  clusterIP: ""
  port: 1812
snmpService:
  create: true
  type: ClusterIP
  clusterIP: ""
  port: 4161
podResources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
dataVolume:
  size: 10Gi
  class: ""
logsVolume:
  size: 10Gi
  class: ""
erlangArgs: ""
ocsConfig:
  create: false
  sysConfig: "[]."
