{{- if .Values.diameterAcctService.create -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-diameter-acct
  labels:
    {{- include "sigscale-ocs.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sigscale-ocs.selectorLabels" . | nindent 6 }}
  type: {{ .Values.diameterAcctService.type }}
  ports:
  - protocol: {{ .Values.diameterAcctService.protocol }}
    appProtocol: diameter
    {{- if .Values.diameterAcctService.clusterIP }}
    clusterIP: {{ .Values.diameterAcctService.clusterIP }}
    {{- end }}
    port: {{ .Values.diameterAcctService.port }}
    targetPort: diameter-acct
{{- end }}
