### Erlang/OTP Distribution Secrets
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-otp-dist
  labels:
    {{- include "sigscale-ocs.labels" . | nindent 4 }}
type: Opaque
data:
  ERLANG_COOKIE: {{ randAlpha 20 | b64enc }}
