##
## Erlang/OTP Cluster Headless Service
##
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-otp-ocs
  labels:
    {{- include "sigscale-ocs.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sigscale-ocs.selectorLabels" . | nindent 6 }}
  type: ClusterIP
  clusterIP: None
